# To run:
#  -  kubectl apply -f docker-node-kubernetes.yaml
# To check status:
#  -  kubectl get deployments
#  -  kubectl get services
# Navigate to `nodePort` to view (http://localhost:30001)
# To delete:
#  -  kubectl delete -f docker-node-kubernetes.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
    name: docker-nodejs-demo
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            todo: web
    template:
        metadata:
            labels:
                todo: web
        spec:
            containers:
                - name: todo-site
                  # dockerhub repo
                  image: cgduzan/docker-nodejs-sample
                  imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: todo-entrypoint
    namespace: default
spec:
    type: NodePort
    selector:
        todo: web
    ports:
        - port: 3000
          targetPort: 3000
          nodePort: 30001
